---
apiVersion: v2
name: vcluster
description: Customized vcluster

version: 1.0.0

type: application

maintainers:
  - name: Daniel Muehlbachler-Pietrzykowski
    email: daniel@muehlbachler.io

appVersion: "0.0.0"

dependencies:
  - name: vcluster
    version: 0.32.0
    repository: https://charts.loft.sh
